version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jmsapp
    depends_on:
#      - activemq
      - rabbitmq
    deploy:
      replicas: 2
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: '1g'

    ports:
      - "28080:8080"
    networks:
      - webnet
    network_mode: global

  kafkaService:
    image: kafkaapp
    depends_on:
      - kafka
#  activemq:
#    image: rmohr/activemq:5.14.3
#    deploy:
#      replicas: 1

#    ports:
#      - "61616:61616"
#      - "8161:8161"
    networks:
      - webnet

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - webnet
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1g'

  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_PORT=9092
      - ADVERTISED_HOST=kafka
#      - JMX_PORT=${JMX_PORT:-9999}
    networks:
      webnet:
        aliases:
          - kafka
    ports:
      - 9092:9092
      - 2181:2181

#
  kafka-manager:
    image: sheepkiller/kafka-manager:stable
    environment:
      - ZK_HOSTS=kafka:2181
      - APPLICATION_SECRET=pass
    networks:
      - webnet
    depends_on:
      - kafka
    ports:
      - 9000:9000
    network_mode: global

networks:
  webnet:


#docker run --name='activemq' -d \
#  -e 'ACTIVEMQ_CONFIG_NAME=amqp-srv1' \
#  -e 'ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false' \
#  -e 'ACTIVEMQ_ADMIN_LOGIN=admin' -e 'ACTIVEMQ_ADMIN_PASSWORD=your_password' \
#  -e 'ACTIVEMQ_USERS_myproducer=producerpassword' -e 'ACTIVEMQ_GROUPS_writes=myproducer' \
#  -e 'ACTIVEMQ_USERS_myconsumer=consumerpassword' -e 'ACTIVEMQ_GROUPS_reads=myconsumer' \
#  -e 'ACTIVEMQ_JMX_user1_role=readwrite' -e 'ACTIVEMQ_JMX_user1_password=jmx_password' \
#  -e 'ACTIVEMQ_JMX_user2_role=read' -e 'ACTIVEMQ_JMX_user2_password=jmx2_password' \
#  -e 'ACTIVEMQ_CONFIG_TOPICS_topic1=mytopic1' -e 'ACTIVEMQ_CONFIG_TOPICS_topic2=mytopic2'  \
#  -e 'ACTIVEMQ_CONFIG_QUEUES_queue1=myqueue1' -e 'ACTIVEMQ_CONFIG_QUEUES_queue2=myqueue2'  \
#  -e 'ACTIVEMQ_CONFIG_MINMEMORY=1024' -e  'ACTIVEMQ_CONFIG_MAXMEMORY=4096' \
#  -e 'ACTIVEMQ_CONFIG_SCHEDULERENABLED=true' \
#  -v /data/activemq:/data \
#  -v /var/log/activemq:/var/log/activemq \
#  -p 8161:8161 \
#  -p 61616:61616 \
#  -p 61613:61613 \
#  webcenter/activemq:5.14.3