apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  containers:
  - image: jmsapp
    name: web
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: 500m
        memory: "1073741824"
  restartPolicy: OnFailure
status: {}
